version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hello, World!"

workflows:
  hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only: main
