version: 2.1

jobs:
  deploy-to-ec2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: SSH into AWS EC2 & Deploy
          command: |
            echo "$EC2_SSH_KEY" > /tmp/aws_ssh_key
            chmod 600 /tmp/aws_ssh_key

            ssh -i /tmp/aws_ssh_key -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP \<< EOF
              echo "Connected to EC2"

              # Build Docker image
              docker build -t my-app:latest .

              # Stop & remove old container
              docker stop my-app-container || true
              docker rm my-app-container || true

              # Run new container with latest build
              docker run -d --name my-app-container -p 80:80 my-app:latest

              echo "Deployment complete!"
            EOF

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - deploy-to-ec2:
          filters:
            branches:
              only: main
